// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRV1OoPshU8sVdBGvDN0Oq9adbLmdC18Y',
    appId: '1:74282556955:web:c5e83a40478d6c7f8962be',
    messagingSenderId: '74282556955',
    projectId: 'post-it-demo',
    authDomain: 'post-it-demo.firebaseapp.com',
    storageBucket: 'post-it-demo.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBG0kJOBGl3Bfm7Gz_ObNwxX7HsAkcgSe8',
    appId: '1:74282556955:android:80861c99c3a4fb2a8962be',
    messagingSenderId: '74282556955',
    projectId: 'post-it-demo',
    storageBucket: 'post-it-demo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0nHeAKgzKgWbqLv8H7g6_Do-ND5dmwdM',
    appId: '1:74282556955:ios:616887602b4000578962be',
    messagingSenderId: '74282556955',
    projectId: 'post-it-demo',
    storageBucket: 'post-it-demo.appspot.com',
    iosClientId: '74282556955-beqbt3oo1l3u8nh80c16b9r18rmndqiv.apps.googleusercontent.com',
    iosBundleId: 'com.example.postit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0nHeAKgzKgWbqLv8H7g6_Do-ND5dmwdM',
    appId: '1:74282556955:ios:616887602b4000578962be',
    messagingSenderId: '74282556955',
    projectId: 'post-it-demo',
    storageBucket: 'post-it-demo.appspot.com',
    iosClientId: '74282556955-beqbt3oo1l3u8nh80c16b9r18rmndqiv.apps.googleusercontent.com',
    iosBundleId: 'com.example.postit',
  );
}
